name: "Styra Init Action"
description: |
  This action runs prerequisite checks to ensure that common (pre)requirements are met.
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      with:
        tool_versions: |
          conftest 0.58.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Run Conftest
      shell: bash
      run: |
        WORKFLOW="$(awk -F '[/@]' '{print $3"/"$4"/"$5}' <<< $WORKFLOW_REF)"
        mise use -g conftest@0.58.0
        conftest test -o github -p "${{ github.action_path }}/policies" $WORKFLOW
      env:
        WORKFLOW_REF: ${{ github.workflow_ref }}
