name: 'Styra Init Action'
description: |
  This action runs prerequisite checks to ensure that common (pre)requirements are met.
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
      with:
        tool_versions: |
          conftest 0.58.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Run Conftest
      shell: bash
      run: |
        WORKFLOW="$(awk -F '[/@]' '{print $3"/"$4"/"$5}' <<< $WORKFLOW_REF)"
        mise use -g conftest@0.58.0
        conftest test -o github -p "${{ github.action_path }}/policies" $WORKFLOW
      env:
       WORKFLOW_REF: ${{ github.workflow_ref }}
