name: 'Styra Init Action'
description: |
  This action runs prerequisite checks to ensure that common (pre)requirements are met.
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # ratchet:jdx/mise-action@v2
      with:
        tool_versions: |
          conftest 0.58.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
    - name: Run Conftest
      shell: bash
      run: |
        mise use -g conftest@0.58.0
        conftest test -o github -p "${{ github.action_path }}/policies" .github/workflows/*
